version: 2.1

orbs:
  tox_orb:
    jobs:
      tox_job:
        parameters:
          tox_name:
            type: string
            default: py27
          tox_args:
            type: string
            default: --
        executor: tox_exec
        steps:
          - tox_pre
          - tox_install
          - tox_run:
              tox_name: <<parameters.tox_name>>
              tox_args: <<parameters.tox_args>>
          - tox_post
    commands:
      tox_pre:
        steps:
          - checkout
          - restore_cache:
              keys:
              - pip-
          - run: pwd
          - run: env
      tox_install:
        steps:
          - run: sudo pip install -U pip setuptools wheel
          - run: sudo pip install -U tox codecov
      tox_run:
        parameters:
          tox_name:
            type: string
            default: py27
          tox_args:
            type: string
            default: --
        steps:
          - run:
              no_output_timeout: 1.5h
              command: tox -e <<parameters.tox_name>> <<parameters.tox_args>>

      tox_post:
        steps:
          - run: codecov
          - save_cache:
              key: pip-{{ epoch}}
              paths:
                - /home/circleci/.cache/pip

    executors:
      tox_exec:
        parameters:
          version:
            type: string
            default: "2.7"
        docker:
          - image: circleci/python:<<parameters.version>>

workflows:
  version: 2
  commit:
    jobs:
      - tox_orb/tox_job:
          name: py27
          tox_name: py27
          #- tox_orb/tox_job:
          #    name: flake8
          #    tox_name: flake8
          #- tox_orb/tox_job:
          #    name: pylint
          #    tox_name: pylint
          #- tox_orb/tox_job:
          #    name: check-manifest
          #    tox_name: check-manifest
          #- tox_orb/tox_job:
          #    name: checkreadme
          #    tox_name: checkreadme

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tox_orb/tox_job:
          name: py27
          tox_name: py27
          #- tox_orb/tox_job:
          #    name: flake8
          #    tox_name: flake8
          #- tox_orb/tox_job:
          #    name: pylint
          #    tox_name: pylint
          #- tox_orb/tox_job:
          #    name: check-manifest
          #    tox_name: check-manifest
          #- tox_orb/tox_job:
          #    name: checkreadme
          #    tox_name: checkreadme
